-- TextureManifest.lua — auto-generated aura-shape library.
-- Source: ThisWeeksAuras Private.texture_types (paths rewritten to GloomsAuras'
-- bundled copies in Media/Textures/ and PowerAurasMedia/Auras/). Regenerate with
-- scratchpad/gen_manifest.py if the bundled art changes.
local GA = _G.GloomsAuras
GA.TextureShapes = {
  { cat = "Shapes", items = {
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Circle_Smooth", name = "Smooth Circle" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Circle_Smooth_Border", name = "Smooth Circle with Border" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Circle_Squirrel", name = "Spiralled Circle" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Circle_Squirrel_Border", name = "Spiralled Circle with Border" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Circle_White", name = "Circle" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Circle_White_Border", name = "Circle with Border" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Square_Smooth", name = "Smooth Square" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Square_Smooth_Border", name = "Smooth Square with Border" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Square_Smooth_Border2", name = "Smooth Square with Border 2" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Square_Squirrel", name = "Spiralled Square" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Square_Squirrel_Border", name = "Spiralled Square with Border" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Square_White", name = "Square" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Square_White_Border", name = "Square with Border" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Square_FullWhite", name = "Full White Square" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Triangle45", name = "45° Triangle" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Trapezoid", name = "Trapezoid" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\triangle-border.tga", name = "Triangle with Border" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\triangle.tga", name = "Triangle" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Circle_Smooth2.tga", name = "Smooth Circle Small" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\circle_border5.tga", name = "Circle Border" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\ring_glow3.tga", name = "Circle Border Glow" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\square_mini.tga", name = "Small Square" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\target_indicator.tga", name = "Target Indicator" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\target_indicator_glow.tga", name = "Target Indicator Glow" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\arrows_target.tga", name = "Arrows Target" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Circle_AlphaGradient_In.tga", name = "Circle Alpha Gradient In" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Circle_AlphaGradient_Out.tga", name = "Circle Alpha Gradient Out" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Ring_10px.tga", name = "Ring 10px" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Ring_20px.tga", name = "Ring 20px" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Ring_30px.tga", name = "Ring 30px" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Ring_40px.tga", name = "Ring 40px" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\Square_AlphaGradient.tga", name = "Square Alpha Gradient" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\square_border_1px.tga", name = "Square Border 1px" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\square_border_5px.tga", name = "Square Border 5px" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\square_border_10px.tga", name = "Square Border 10px" },
  } },
  { cat = "PowerAuras Heads-Up", items = {
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura1", name = "Runed Text" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura2", name = "Runed Text On Ring" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura3", name = "Power Waves" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura4", name = "Majesty" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura5", name = "Runed Ends" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura6", name = "Extra Majesty" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura7", name = "Triangular Highlights" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura11", name = "Oblong Highlights" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura16", name = "Thin Crescents" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura17", name = "Crescent Highlights" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura18", name = "Dense Runed Text" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura23", name = "Runed Spiked Ring" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura24", name = "Smoke" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura28", name = "Flourished Text" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura33", name = "Droplet Highlights" },
  } },
  { cat = "PowerAuras Icons", items = {
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura8", name = "Rune" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura9", name = "Stylized Ghost" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura10", name = "Skull and Crossbones" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura12", name = "Snowflake" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura13", name = "Flame" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura14", name = "Holy Rune" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura15", name = "Zig-Zag Exclamation Point" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura19", name = "Crossed Swords" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura21", name = "Shield" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura22", name = "Glow" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura25", name = "Cross" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura26", name = "Droplet" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura27", name = "Alert" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura29", name = "Paw" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura30", name = "Bull" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura32", name = "Hieroglyphics" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura34", name = "Circled Arrow" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura35", name = "Short Sword" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura45", name = "Circular Glow" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura48", name = "Totem" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura49", name = "Dragon Blade" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura50", name = "Ornate Design" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura51", name = "Inverted Holy Rune" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura52", name = "Stylized Skull" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura53", name = "Exclamation Point" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura54", name = "Nonagon" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura68", name = "Wings" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura69", name = "Rectangle" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura70", name = "Low Mana" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura71", name = "Ghostly Eye" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura72", name = "Circle" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura73", name = "Ring" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura74", name = "Square" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura75", name = "Square Brackets" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura76", name = "Bob-omb" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura77", name = "Goldfish" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura78", name = "Check" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura79", name = "Ghostly Face" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura84", name = "Overlapping Boxes" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura87", name = "Fairy" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura88", name = "Comet" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura95", name = "Dual Spiral" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura96", name = "Japanese Character" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura97", name = "Japanese Character" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura98", name = "Japanese Character" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura99", name = "Japanese Character" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura100", name = "Japanese Character" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura101", name = "Ball of Flame" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura102", name = "Zig-Zag" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura103", name = "Thorny Ring" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura110", name = "Hunter's Mark" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura112", name = "Kaleidoscope" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura113", name = "Jesus Face" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura114", name = "Green Mushroom" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura115", name = "Red Mushroom" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura116", name = "Fire Flower" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura117", name = "Radioactive" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura118", name = "X" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura119", name = "Flower" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura120", name = "Petal" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura130", name = "Shoop Da Woop" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura131", name = "8-Bit Symbol" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura132", name = "Cartoon Skull" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura138", name = "Stop" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura139", name = "Thumbs Up" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura140", name = "Palette" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura141", name = "Blue Ring" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura142", name = "Ornate Ring" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura143", name = "Ghostly Skull" },
  } },
  { cat = "PowerAuras Separated", items = {
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura46", name = "8-Part Ring 1" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura47", name = "8-Part Ring 2" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura55", name = "Skull on Gear 1" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura56", name = "Skull on Gear 2" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura57", name = "Skull on Gear 3" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura58", name = "Skull on Gear 4" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura59", name = "Rune Ring Full" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura60", name = "Rune Ring Empty" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura61", name = "Rune Ring Left" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura62", name = "Rune Ring Right" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura63", name = "Spiked Rune Ring Full" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura64", name = "Spiked Rune Ring Empty" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura65", name = "Spiked Rune Ring Left" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura66", name = "Spiked Rune Ring Bottom" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura67", name = "Spiked Rune Ring Right" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura80", name = "Spiked Helm Background" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura81", name = "Spiked Helm Full" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura82", name = "Spiked Helm Bottom" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura83", name = "Spiked Helm Top" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura89", name = "5-Part Ring 1" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura90", name = "5-Part Ring 2" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura91", name = "5-Part Ring 3" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura92", name = "5-Part Ring 4" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura93", name = "5-Part Ring 5" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura94", name = "5-Part Ring Full" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura104", name = "Shield Center" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura105", name = "Shield Full" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura106", name = "Shield Top Right" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura107", name = "Shield Top Left" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura108", name = "Shield Bottom Right" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura109", name = "Shield Bottom Left" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura121", name = "Vine Top Right Leaf" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura122", name = "Vine Left Leaf" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura123", name = "Vine Bottom Right Leaf" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura124", name = "Vine Stem" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura125", name = "Vine Thorns" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura126", name = "3-Part Circle 1" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura127", name = "3-Part Circle 2" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura128", name = "3-Part Circle 3" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura129", name = "3-Part Circle Full" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura133", name = "Sliced Orb 1" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura134", name = "Sliced Orb 2" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura135", name = "Sliced Orb 3" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura136", name = "Sliced Orb 4" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura137", name = "Sliced Orb 5" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura144", name = "Taijitu Bottom" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura145", name = "Taijitu Top" },
  } },
  { cat = "PowerAuras Words", items = {
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura20", name = "Power" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura37", name = "Slow" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura38", name = "Stun" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura39", name = "Silence" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura40", name = "Root" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura41", name = "Disorient" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura42", name = "Dispel" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura43", name = "Danger" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura44", name = "Buff" },
    { tex = "Interface\\Addons\\GloomsAuras\\PowerAurasMedia\\Auras\\Aura44", name = "Buff" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\interrupt", name = "Interrupt" },
    { tex = "==", name = "=" },
    { tex = "~=", name = "!=" },
    { tex = ">", name = ">" },
    { tex = "<", name = "<" },
    { tex = ">=", name = ">=" },
    { tex = "<=", name = "<=" },
    { tex = "==", name = "=" },
    { tex = "~=", name = "!=" },
    { tex = ">=", name = ">=" },
    { tex = "<=", name = "<=" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\stopmotion", name = "Example" },
  } },
  { cat = "Beams", items = {
    { tex = "167096", name = "Gold Chain" },
    { tex = "167097", name = "Iron Chain" },
    { tex = "167098", name = "Green Fire Beam" },
    { tex = "167099", name = "Red Fire Beam" },
    { tex = "167100", name = "Brown Smoke Beam" },
    { tex = "167101", name = "Grey Smoke Beam" },
    { tex = "167102", name = "Green Vine" },
    { tex = "167103", name = "Red Vine" },
    { tex = "167104", name = "Blue Water Beam" },
    { tex = "167105", name = "Green Water Beam" },
    { tex = "186185", name = "Purple Beam" },
    { tex = "186186", name = "Red Beam" },
    { tex = "186187", name = "Red Drops Beam" },
    { tex = "186189", name = "Drain Mana Lightning" },
    { tex = "186192", name = "Ethereal Ribbon" },
    { tex = "186193", name = "Ghost Chain" },
    { tex = "186194", name = "Purple Ghost Chain" },
    { tex = "186195", name = "Heal Beam" },
    { tex = "186198", name = "Lightning" },
    { tex = "186201", name = "Red Lightning" },
    { tex = "186202", name = "Mana Beam" },
    { tex = "186205", name = "Mana Burn Beam" },
    { tex = "186208", name = "Rope" },
    { tex = "186211", name = "Shock Lightning" },
    { tex = "186214", name = "Soul Beam" },
    { tex = "241098", name = "Spirit Link Beam" },
    { tex = "241099", name = "Summon Gargoyle Beam" },
    { tex = "369749", name = "Straight Purple Beam" },
    { tex = "369750", name = "Shadow Beam" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\rainbowbar", name = "Rainbow Bar" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\StripedTexture", name = "Striped Bar" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\stripe-bar.tga", name = "Striped Bar 2" },
    { tex = "Interface\\AddOns\\GloomsAuras\\Media\\Textures\\stripe-rainbow-bar.tga", name = "Rainbow Bar 2" },
  } },
  { cat = "Sparks", items = {
    { tex = "130877", name = "Blizzard Spark" },
    { tex = "Insanity-Spark", name = "Blizzard Insanity Spark" },
    { tex = "XPBarAnim-OrangeSpark", name = "Blizzard XPBar Spark" },
    { tex = "GarrMission_EncounterBar-Spark", name = "Blizzard Garrison Mission Encounter Spark" },
    { tex = "Legionfall_BarSpark", name = "Blizzard Legionfall Spark" },
    { tex = "honorsystem-bar-spark", name = "Blizzard Honor System Spark" },
    { tex = "bonusobjectives-bar-spark", name = "Bonus Objectives Spark" },
  } },
  { cat = "Runes", items = {
    { tex = "165630", name = "Ringed Aura Rune" },
    { tex = "165631", name = "Square Aura Rune" },
    { tex = "165633", name = "Tri-Circle Aura Rune" },
    { tex = "165634", name = "Tri-Circle Ringed Aura Rune" },
    { tex = "165635", name = "Spike-Ringed Aura Rune" },
    { tex = "165638", name = "Small Tri-Circle Aura Rune" },
    { tex = "165639", name = "Sliced Aura Rune" },
    { tex = "165640", name = "Oblong Aura Rune" },
    { tex = "165881", name = "Dark Summon" },
    { tex = "165885", name = "Death Rune" },
    { tex = "165922", name = "Demonic Summon" },
    { tex = "165927", name = "Demon Rune" },
    { tex = "165928", name = "Demon Rune" },
    { tex = "165929", name = "Demon Rune" },
    { tex = "166340", name = "Holy Rune" },
    { tex = "166341", name = "Holy Cross Rune" },
    { tex = "166748", name = "Filled Circular Rune" },
    { tex = "166749", name = "Ringed Circular Rune" },
    { tex = "166750", name = "Sparse Circular Rune" },
    { tex = "166753", name = "Heavy BC Rune" },
    { tex = "166754", name = "Light BC Rune" },
    { tex = "166757", name = "Circular Frost Rune" },
    { tex = "166979", name = "Star Rune" },
    { tex = "241003", name = "Dual Blades" },
    { tex = "241004", name = "Octagonal Skulls" },
    { tex = "241005", name = "Dense Circular Rune" },
  } },
}
